# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Threebit.OutaStory
PackageVersion: 1.9.41.247
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: io.threebit.outastory_x1n4bg2pjdgww
Installers:
- Architecture: x64
  InstallerUrl: https://download.outastory.com/windows/1.9.41/OutaStory-1.9.41.msixbundle
  InstallerSha256: BDEC873A622683CDE2E118AA40216E8864E6E1AAFF12745AFFD1643F1F80F77B
  SignatureSha256: BB9F083C107A2A99F0844790301AC70273B534C665C4900B1D2D8A90E6EC3737
- Architecture: arm64
  InstallerUrl: https://download.outastory.com/windows/1.9.41/OutaStory-1.9.41.msixbundle
  InstallerSha256: BDEC873A622683CDE2E118AA40216E8864E6E1AAFF12745AFFD1643F1F80F77B
  SignatureSha256: BB9F083C107A2A99F0844790301AC70273B534C665C4900B1D2D8A90E6EC3737
ManifestType: installer
ManifestVersion: 1.12.0
