# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Threebit.OutaStory
PackageVersion: 1.9.36.242
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: io.threebit.outastory_x1n4bg2pjdgww
Installers:
- Architecture: x64
  InstallerUrl: https://download.outastory.com/windows/1.9.36/OutaStory-1.9.36.msixbundle
  InstallerSha256: F286FC5B17978C15F9C24895A47C08440FEC1F8639497044D9C2724F1DC1D462
  SignatureSha256: 0B79EEE822A38C2D039E210634B3BA7DF361584A96429D7B7A69121FE8E00AA3
- Architecture: arm64
  InstallerUrl: https://download.outastory.com/windows/1.9.36/OutaStory-1.9.36.msixbundle
  InstallerSha256: F286FC5B17978C15F9C24895A47C08440FEC1F8639497044D9C2724F1DC1D462
  SignatureSha256: 0B79EEE822A38C2D039E210634B3BA7DF361584A96429D7B7A69121FE8E00AA3
ManifestType: installer
ManifestVersion: 1.12.0
