# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Threebit.OutaStory
PackageVersion: 1.9.39.245
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: io.threebit.outastory_x1n4bg2pjdgww
Installers:
- Architecture: x64
  InstallerUrl: https://download.outastory.com/windows/1.9.39/OutaStory-1.9.39.msixbundle
  InstallerSha256: 95F9D2EC62B6187F18CEA98E22B393B6D2FCC77C0AE9B47B19E6B5803BEB996A
  SignatureSha256: F3EEDA526B404452E1F49564E357A7FA8DDD5AF0BCB805BA7AFF733D9A14D890
- Architecture: arm64
  InstallerUrl: https://download.outastory.com/windows/1.9.39/OutaStory-1.9.39.msixbundle
  InstallerSha256: 95F9D2EC62B6187F18CEA98E22B393B6D2FCC77C0AE9B47B19E6B5803BEB996A
  SignatureSha256: F3EEDA526B404452E1F49564E357A7FA8DDD5AF0BCB805BA7AFF733D9A14D890
ManifestType: installer
ManifestVersion: 1.12.0
